### PR TITLE
Misc sprite fixes and portal storm placeholder

### PR DESCRIPTION
**Pull request by TheLyca0n**
Portal placeholder,Exodii quad temp fix, modified xotto rubik sprite, Couple of Feral sprites added hoping to add a good few  more (Mechanic,Cunning and single soldier hoping for varients to that) and stubby tail now matches description.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Sprites taken from MSX need to be on their own tilesheet with a clear mention of their license and source

**Comment by Fris0uman** [comment]
Even if you use it as a placeholder you still have to follow the license if you want to redistribute it. Unless you mean that you're going to replace by something else before merging this pull request

**Comment by SzQ1** [comment]
Not sure if merging this PR after my #31 will not break the Temporary.png, if it will @ me on discord I will make quick fix PR.

**Comment by TheLyca0n** [comment]
> Not sure if merging this PR after my #31 will not break the Temporary.png, if it will @ me on discord I will make quick fix PR.

Nah your cool the fix is as simple as me importing your sprites and allocating them after mine. Will have them compatible by this evening after the crazed preppers and survivalists are done, don't cock up your work on my behalf 🤣

**Pull request closed without merging**
