### PR TITLE
New Dinomod shady sprites

### PR DESCRIPTION
**Pull request by SzQ1**
mon_zyrannosaurus_shady, mon_zeinonychus_shady, mon_zallosaurus_shady, mon_zutahraptor_shady, mon_zacrocanthosaurus_shady.
Also linted the dinomod json since I'm still manual editing it like a caveman.

### CODE REVIEW

**Comment by LyleSY** [comment]
Looks great, and also a good kick in the head that I need to finish building out the shadies. I could have sworn I already had shady acrocanthosaurus
DinoMod_huge

**Comment by LyleSY** [comment]
The json could probably benefit from linting but I don't see it breaking anything

**Review by LyleSY — APPROVED** [review]

**Comment by Theawesomeboophis** [comment]
> The json could probably benefit from linting but I don't see it breaking anything

It was already linted, did it somehow unlint itself?

**Comment by LyleSY** [comment]
That's what I see, though I can't explain it

**Pull request merged**
