### PR TITLE
 GO specific parking lots and roads

### PR DESCRIPTION
**Pull request by SzQ1**
Parking lots and roads in industrial centres, mines, etc. Just one tile_config.json change, further change need to be done in BN and DDA, I will link here the BN PR later.

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
I'll wait until Lycaon's update before merging, but great job with this.

**Comment by Theawesomeboophis** [comment]
Just realized it's just json change.

**Comment by SzQ1** [comment]
Related BN PR
https://github.com/SzQ1/Cataclysm-BN/pull/2

**Comment by SzQ1** [comment]
Related BN PR
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1563

**Pull request merged**
