### PR TITLE
Update tile_config.json

### PR DESCRIPTION
**Pull request by drabont7**
fixed: some machines installed as _appliances_ are displayed incorrectly
before

after

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
This will also need to be fixed in unpacked before merge to prevent desync and other issues.

**Comment by Theawesomeboophis** [comment]
Otherwise, this PR will be overwritten next update.

**Comment by Theawesomeboophis** [comment]
Fixed in unpacked. Merging, are you on the discord so I can give you contributor?

**Comment by drabont7** [comment]
not need, thanks for your work.

**Pull request merged**
