### PR TITLE
Tileset contribution

### PR DESCRIPTION
**Pull request by Coligad**
normal

### CODE REVIEW

**Comment by Theawesomeboophis** [comment]
It looks like you accidentally put the png as the description.

**Comment by Theawesomeboophis** [comment]
File should be moved to same folder as config. If you have any questions, join the discord or at me on github if you're more comfortable communicating that way.

**Comment by Coligad** [comment]
> File should be moved to same folder as config. If you have any questions, join the discord or at me on github if you're more comfortable communicating that way.

What do you by config?

**Comment by Theawesomeboophis** [comment]
The Png is not in the mod folder with config, so it won't activate, I recommend moving the png to the same folder as the mod on your local computer, deleting the old png, and submitting the mod folder to github.

**Review by Coligad — COMMENTED** [review]
normal

**Review by Coligad — COMMENTED** [review]
normal

**Pull request closed without merging**
